spring:
  http:
    converters:
      preferred-json-mapper: gson
debug: false
logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
org:
  springframework:
    boot:
      logging:
        LoggingSystem: none
jar:
  path:
# TODO Actual values for domain and url need to be provided
activedirectory:
  domain: "ERICSSON.COM"
  url: "ldap://<hostname>.ericsson.com"